version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - postgres_network

volumes:
  pgdata:

networks:
  postgres_network:
    driver: bridge
